version: "3.4"

services:
  postgres:
    container_name: postgres
    image: postgres:12.2
    restart: always
    volumes:
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgres/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: gin_gorm

#  gin-gorm-server:
#    build:
#      context: ../..
#      dockerfile: Dockerfile
#      target: development
#    container_name: gin-gorm
#    ports:
#      - "8001:8001"
#    depends_on:
#      - postgres
#    environment:
#      POSTGRES_HOST: postgres
#      POSTGRES_PORT: 5432
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: mypass
#      POSTGRES_DB: gin_gorm
